add_executable(renderer
    main.cpp
    shader.cpp
    texture.cpp
    window.cpp
    mesh.cpp
    model.cpp
    camera.cpp
    scene.cpp
    debug_window.cpp
    fps_tracker.cpp
    skybox.cpp
    image_data.cpp
)

target_include_directories(renderer
    PRIVATE
    ${CMAKE_SOURCE_DIR}/include
    ${CMAKE_SOURCE_DIR}/thirdparty
)

target_link_libraries(renderer
    PRIVATE
    glad_gl_core_33
    glfw
    glm::glm
    assimp
    imgui
    ImGuiFileDialog
)
